import Head from "next/head";
import { Inter } from "@next/font/google";
import LanguageSwitcher from "../components";
import { useState } from "react";
import Router from "next/router";
import { createUseStyles } from "react-jss";
import { useTranslation } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [isModalOpen, setIsModalOpen] = useState(false);

  const checkIfOpenModal = () => {
    if (!isModalOpen) return;
    if (isModalOpen) {
      setIsModalOpen(false);
    }
  };

  const { t, i18n } = useTranslation("common");

  return (
    <>
      <Head>
        <title>Translate app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div onClick={checkIfOpenModal}>
        <LanguageSwitcher isOpen={isModalOpen} content={t("text.translate")} />
      </div>
      <div>{t("translate")}</div>
    </>
  );
}

export async function getStaticProps({ locale }: any) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ["common"])),
    },
  };
}
